db:
  dsn: "root:root@tcp(localhost:13316)/webook_comment"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    port: 8093
    etcdAddr: "localhost:12379"
    etcdTTL: 60
etcd:
  endpoints:
    - "localhost:12379"
