http:
  addr: ":8080"
etcd:
  endpoints:
    - "localhost:12379"
grpc:
  client:
    user:
      target: "etcd:///service/user"
    article:
      target: "etcd:///service/article"
    code:
      target: "etcd:///service/code"
    intr:
      target: "etcd:///service/interactive"
    reward:
      target: "etcd:///service/reward"
    ranking:
      target: "etcd:///service/ranking"
    comment:
      target: "etcd:///service/comment"
    follow:
      target: "etcd:///service/follow"
    tag:
      target: "etcd:///service/tag"
