db:
  dsn: "root:root@tcp(localhost:13316)/webook"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    port: 8090
    etcdAddr: "localhost:12379"
    etcdTTL: 60
etcd:
  endpoints:
    - "localhost:12379"
es:
  url: "http://localhost:9200"
  sniff: false
