db:
  src:
    dsn: "root:root@tcp(localhost:13316)/webook_intr"
#    这里后续如果想测试表数据迁移可以走这里webook就行
  dst:
    dsn : "root:root@tcp(localhost:13316)/webook_intr"
redis:
  addr: "localhost:6379"
kafka:
  addrs:
  - "localhost:9094"
etcd:
  endpoints:
    - "localhost:12379"
grpc:
  server:
    port: 8094
    etcdAddr: "localhost:12379"
    etcdTTL: 60
migrator:
  http:
    addr: ":8082"