grpc:
  #  启动监听 9001 端口
  server:
    port: 8088
    etcdAddr: "localhost:12379"
    etcdTTL: 60

etcd:
  endpoints:
    - "localhost:12379"
db:
  dsn: "root:root@tcp(localhost:13316)/webook_sms"
tencentSms:
  secretId: "xxxxxx"
  secretKey: "oooooo"
