db:
  dsn: "root:root@tcp(localhost:13316)/webook_follow"

grpc:
  server:
    port: 8099
    etcdAddr: "localhost:12379"
    etcdTTL: 60
redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

etcd:
  endpoints:
    - "localhost:12379"

