redis:
  addr: "localhost:6379"

grpc:
  server:
    port: 8092
    etcdAddr: "localhost:12379"
    etcdTTL: 60
  client:
    intr:
      addr: ":8094"
    article:
      target: "etcd:///service/article"
      secure: false
etcd:
  endpoints:
    - "localhost:12379"